# Generated by Django 5.2.4 on 2025-10-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.URLField(blank=True)),
            ],
        ),
    ]
